[package]
name = "gamepad_motion"
description = "Rust bindings for GampadMotionHelpers."
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx = "0.26.0"
cxx = "1.0.109"

[build-dependencies]
autocxx-build = "0.26.0"
